version: "3.8"

services:
  mysql.db:
    container_name: mysql.db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "Admin@123$"
      MYSQL_TCP_PORT: 3306
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
